[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  NODE_VERSION = "20"
[build]
  command = "npm install && npm run build"
  commandOrigin= "config"
  functions = "functions"
  publish= "/opt/build/repo"
  publishOrigin= "ui"
  functionsDirectory= "/opt/build/repo/functions"
